[servers:children]
update_monday
update_wednesday
update_saturday

[update_monday]
# server1.example.com

[update_wednesday]
# server2.example.com

[update_saturday]
# server3.example.com

[servers:vars]
ansible_user=root
